### PR TITLE
Add additional bank configuration items

### PR DESCRIPTION
**Pull request by Herrie82**
For a prettier generation of bank letters and other bits used in examples:

* Added a French template based on implementation guide with French example from ABACUS Research SA.

Expand the bank config to include:

* "bankFullName" used in the INI letter's which are sent to the bank.
* "bankShortName" used in the filename for the generated letters and in other places if needed.
* "languageCode" used for determining which template to use for the bank (currently "en" and "de" are supported).
* "storageLocation" can be used to specify a local or network path where to store downloaded files.

* In bankLetter.js: Use the current script folder as output for the bank's letter in HTML format instead of the user/os homedir folder.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by Herrie82** [comment]
@nanov I will expand the examples with usage of "storageLocation" after this and other PR's are merged.

**Comment by nanov** [comment]
The only comment I have here, is why introduce braking change and remove `bankName` instead of just adding `bankFullNme` or alternatively `bankShortName` ( seems and the current one should bet the full one already ), and defaulting the one to the other if not present? ( ie. `bankShortName =  bankShortName || bankFullName` ).

**Comment by Herrie82** [comment]
> The only comment I have here, is why introduce braking change and remove `bankName` instead of just adding `bankFullNme` or alternatively `bankShortName` ( seems and the current one should bet the full one already ), and defaulting the one to the other if not present? ( ie. `bankShortName = bankShortName || bankFullName` ).

bankShortName would be a name that doesn't contain any whitespace, so either the BIC or an abbreviation that could then be used in generated filenames for example (such as bank letter or downloaded CAMT/MT940 files). I will expand the examples a bit once this has been merged.

I thought to change bankName into bankFullName to avoid any confusion and it's more clear. Similar like you changed the config items from "serverAddress" into "url" and "keyStorage" into "keyStoragePath".

**Comment by nanov** [comment]
> I thought to change bankName into bankFullName to avoid any confusion and it's more clear. Similar like you changed the config items from "serverAddress" into "url" and "keyStorage" into "keyStoragePath".

leaving bankName as is and NOT introducing breaking changes seems a cleaner solution.

**Comment by Herrie82** [comment]
> > I thought to change bankName into bankFullName to avoid any confusion and it's more clear. Similar like you changed the config items from "serverAddress" into "url" and "keyStorage" into "keyStoragePath".
> 
> leaving bankName as is and NOT introducing breaking changes seems a cleaner solution.

Yes and no ;) I can update bankName to bankFullName in everywhere it occurs (so the various js files related to BankLetter (which is the only place it's being used anyway for the moment). Or keep it bankName, up to you in the end.

**Comment by Herrie82** [comment]
@nanov This should be good to go now

**Pull request merged**
